### PR TITLE
Update datastream file fixtures

### PR DESCRIPTION
**Pull request by akofink**
I'm expecting tests to fail here. @xprazak2 you wrote some of the [failing validations](https://github.com/dLobatog/openscap_parser/blob/master/lib/openscap_parser/ds.rb#L17) - I wonder if you based the namespace requirement on the SCAP spec or just from an example datastream file? These three datastreams were downloaded from the ComplianceAsCode repo's latest release: https://github.com/ComplianceAsCode/content/releases/download/v0.1.46/scap-security-guide-0.1.46.zip

None of the three are 'valid' as written:

```rb
[1] pry(#<DsTest>)> create_parser('ssg-rhel7-ds.xml').valid?
=> false
[2] pry(#<DsTest>)> create_parser('ssg-rhel6-ds.xml').valid?
=> false
[3] pry(#<DsTest>)> create_parser('ssg-rhel8-ds.xml').valid?
=> false
```

Signed-off-by: Andrew Kofink <akofink@redhat.com>

### CODE REVIEW

**Comment by akofink** [comment]
It does, but the validation looking for namespaces still fails. I need to figure this out.

**Comment by xprazak2** [comment]
@akofink, I just took it from the file. The check is failing because the new file contains completely different namespaces:

ds-before

ds-after

maybe because scap-version changed to 1.3?

**Comment by akofink** [comment]
Right, so my question is about the namespaces. Why did we add the validations there? Is it okay to remove the namespace validation now?

**Comment by xprazak2** [comment]
I think you can remove them if it helps you move forward. I wanted some basic check that the file is really what we expect so I added validations for namespaces, because I did not think they would change.

**Comment by akofink** [comment]
Finally updated. The list of profiles was missing one for `xccdf_org.ssgproject.content_profile_pci-dss_centric` which has the same title as `xccdf_org.ssgproject.content_profile_pci-dss`.

**Comment by akofink** [comment]
Rebased

**Pull request merged**
